import React from 'react';
import { CalendarClock, ChevronRight } from 'lucide-react';
import { dropSchedule } from '../adminData.js';
import { SectionHeader } from '../components/AdminUi.jsx';

export function AdminDrops() {
  return (
    <div className="admin-page-stack">
      <SectionHeader eyebrow="Drop operations" title="드롭 운영" description="판매 일정, 오픈 준비 상태와 재고 배분을 관리합니다." action={<button className="admin-primary-button" type="button"><CalendarClock size={16} /> 새 드롭 만들기</button>} />
      <section className="admin-drop-hero"><div><span className="admin-live-pill dark"><span /> NEXT DROP</span><h2>Archive Drop 07</h2><p>오픈까지 <strong>05:27:18</strong></p><div className="admin-drop-stats"><span>상품 <b>4종</b></span><span>총 재고 <b>500개</b></span><span>대기 고객 <b>2,840명</b></span></div></div><div className="admin-launch-ring"><strong>72%</strong><span>준비 완료</span></div></section>
      <section className="admin-drop-grid"><article className="admin-card"><div className="admin-card-head"><div><span className="admin-card-kicker">LAUNCH CHECKLIST</span><h3>오픈 체크리스트</h3></div><span className="admin-count-badge">6 / 8</span></div><div className="admin-launch-list"><label><input type="checkbox" defaultChecked /><span><strong>상품 정보 및 이미지 검수</strong><small>콘텐츠팀 · 완료</small></span></label><label><input type="checkbox" defaultChecked /><span><strong>재고 수량 및 구매 제한 설정</strong><small>상품팀 · 완료</small></span></label><label><input type="checkbox" defaultChecked /><span><strong>결제사 점검 및 테스트 결제</strong><small>개발팀 · 완료</small></span></label><label><input type="checkbox" /><span><strong>트래픽 스케일링 사전 점검</strong><small>인프라팀 · 확인 필요</small></span></label><label><input type="checkbox" /><span><strong>고객 공지 및 알림 발송</strong><small>마케팅팀 · 대기</small></span></label></div></article><article className="admin-card"><div className="admin-card-head"><div><span className="admin-card-kicker">STOCK ALLOCATION</span><h3>재고 배분</h3></div><button className="admin-text-button" type="button">수정</button></div><div className="admin-allocation-list"><div><span>Archive Varsity Jacket<small>구매 제한 1개</small></span><strong>100개</strong><b><i style={{ width: '20%' }} /></b></div><div><span>Founders Hoodie<small>구매 제한 2개</small></span><strong>200개</strong><b><i style={{ width: '40%' }} /></b></div><div><span>Numbered Tote<small>구매 제한 1개</small></span><strong>150개</strong><b><i style={{ width: '30%' }} /></b></div><div><span>Archive Ball Cap<small>구매 제한 2개</small></span><strong>50개</strong><b><i style={{ width: '10%' }} /></b></div></div></article></section>
      <section className="admin-card admin-schedule-card"><div className="admin-card-head"><div><span className="admin-card-kicker">DROP CALENDAR</span><h3>예정된 드롭</h3></div></div><div className="admin-schedule-list">{dropSchedule.map((drop) => <button type="button" key={drop.name}><span className="admin-schedule-date"><CalendarClock size={18} /></span><span><strong>{drop.name}</strong><small>{drop.date} · 상품 {drop.products}종 · 재고 {drop.stock}개</small></span><span className="admin-progress"><b><i style={{ width: `${drop.progress}%` }} /></b><small>{drop.progress}% 준비</small></span><span className={`admin-drop-status ${drop.status === '검수 필요' ? 'warning' : ''}`}>{drop.status}</span><ChevronRight size={17} /></button>)}</div></section>
    </div>
  );
}
